### ISSUE TITLE
requirements.txt file issues

### ISSUE THREAD

**Issue by ghost** [ericsalesdeandrade/pytest-fastapi-crud-example#1]
When doing a pip install -r requirements.txt with your file on my m1 mac with a virtualenv set up, I got failures. Looking at the file it seems there are quite a few unnecessary packages there, including the one that failed.
So I started minimal and installed each missing package found when running the unit test.

The result is a much more minimal file, and it works.
`
anyio==3.7.0
certifi==2023.5.7
fastapi==0.95.2
fastapi-utils==0.2.1
h11==0.14.0
httpcore==0.17.2
httpx==0.24.1
idna==3.4
iniconfig==2.0.0
packaging==23.1
pluggy==1.0.0
pydantic==1.10.8
pytest==7.3.1
sniffio==1.3.0
SQLAlchemy==1.4.48
starlette==0.27.0
typing_extensions==4.6.2
`

**Comment by ericsalesdeandrade** [comment]
Thanks, @tcooperFL I'll take a look. I use an Intel Mac so didn't have any issues 👍

**Comment by ericsalesdeandrade** [comment]
Hey this is cleaned up now. Closing the issue.
